name: yogathon_registration
description: Demonstrates how to use the mobile_scanner plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  http: ^0.13.5
  gsheets: ^0.4.2
  fluttertoast: ^8.1.1

  mobile_scanner:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
